Repository fredyalarcon/ing-sw-apps-moviles-hfmn, pull requests merged in 2023-11, with the labels that each got.

#47 Bugfix/45 bug hu001 mensaje cuando lista albumes vacia 1
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/ui/AlbumFragment.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/viewmodels/AlbumViewModel.kt
  app/src/main/res/layout/album_fragment.xml
  app/src/main/res/values/strings.xml
Labels: bug

#48 Se crea un paquete "repositories" y se adiciona el archivo AlbumRepos…
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/repositories/AlbumRepository.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/viewmodels/AlbumViewModel.kt
Labels: feature

#52 feature/3-hu003-Servicio-API-listar-artistas
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/models/Band.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/models/Musician.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/models/Performer.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/ui/adapters/BandsAdapter.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/ui/adapters/MusiciansAdapter.kt
Labels: feature

#54 Feature/16 hu003 vista listar artistas
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/repositories/MusiciansRepository.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/ui/AlbumFragment.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/ui/ArtistFragment.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/ui/adapters/MusiciansAdapter.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/viewmodels/ArtistViewModel.kt
  app/src/main/res/layout/activity_access.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/album_fragment.xml
  app/src/main/res/layout/album_item.xml
  app/src/main/res/layout/artist_fragment.xml
  app/src/main/res/layout/artist_item.xml
  app/src/main/res/layout/menu_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, feature

#57 Feature/16 hu003 actualizar readme
  README.md
  app/build.gradle
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/network/NetworkServiceAdapter.kt
Labels: documentation

#66 feature: Crear layout formulario crear album #25
  app/build.gradle
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/ui/AlbumCreateFragment.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/ui/AlbumFragment.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/ui/MainActivity.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/ui/PerformerFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/album_create_fragment.xml
  app/src/main/res/layout/performer_fragment.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#68 Feature/67 corrutinas listar albums y artistas
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/network/MockNetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/repositories/AlbumRepository.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/repositories/PerformerRepository.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/viewmodels/AlbumViewModel.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/viewmodels/PerformerViewModel.kt
Labels: feature

#93 feature: listar tracks de un album #34
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/models/Track.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/repositories/TrackRepository.kt
  app/src/main/java/co/edu/uniandes/miswmobile/vinilosapp/viewmodels/TrackViewModel.kt
Labels: feature
